# Gunakan image resmi PHP 8.1 dengan Apache
FROM php:8.1-apache

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

RUN apt-get update
RUN apt-get install -y libpq-dev libzip-dev libpng-dev libjpeg-dev libwebp-dev libicu-dev libxml2-dev unzip libc6 libaio1 curl libcurl4-openssl-dev libonig-dev libbz2-dev libfreetype6-dev libmcrypt-dev libreadline-dev libedit-dev libffi-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./instantclient/instantclient-basic-linux.x64-21.12.0.0.0dbru.zip /tmp/
COPY ./instantclient/instantclient-sdk-linux.x64-21.12.0.0.0dbru.zip /tmp/
COPY ./instantclient/instantclient-sqlplus-linux.x64-21.12.0.0.0dbru.zip /tmp/

# unzip them
RUN unzip /tmp/instantclient-basic-linux.x64-*.zip -d /usr/local/ \
    && unzip /tmp/instantclient-sdk-linux.x64-*.zip -d /usr/local/ \
    && unzip /tmp/instantclient-sqlplus-linux.x64-*.zip -d /usr/local/

# install oci8
RUN ln -s /usr/local/instantclient_21_12 /usr/local/instantclient \
    && ln -s /usr/local/instantclient/sqlplus /usr/bin/sqlplus 

RUN docker-php-ext-configure oci8 --with-oci8=instantclient,/usr/local/instantclient
RUN docker-php-ext-install oci8
RUN echo /usr/local/instantclient/ > /etc/ld.so.conf.d/oracle-instantclient.conf
RUN ldconfig
    
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-configure  gd --with-webp

# Instal ekstensi PHP yang diperlukan untuk pengembangan
RUN docker-php-ext-install mysqli pdo pdo_mysql pdo_pgsql pgsql zip gd intl gettext xml curl exif

# Aktifkan mod_rewrite untuk Apache
RUN a2enmod rewrite headers deflate expires authz_core authz_groupfile setenvif 

# Set konfigurasi virtual host Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Aktifkan konfigurasi virtual host yang baru
RUN a2ensite 000-default.conf

# Restart Apache untuk menerapkan perubahan
RUN service apache2 restart

# Set folder proyek sebagai volume
VOLUME /var/www/html