version: '3'

services:
  php-7.4:
    build:
      context: .
      dockerfile: Dockerfile-7.4
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=512M
  php-8.1:
    build:
      context: .
      dockerfile: Dockerfile-8.1
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=512M
  php-8.2:
    build:
      context: .
      dockerfile: Dockerfile-8.2
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=512M
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qc7nry3o47cynr
      MYSQL_USER: userdb
      MYSQL_PASSWORD: qc7nry3o47cynr
    volumes:
      - ./data:/var/lib/mysql