# Gunakan image resmi PHP 8.2 dengan Apache
FROM php:8.2-apache

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

RUN apt-get update
RUN apt-get install -y libpq-dev libzip-dev libpng-dev libjpeg-dev libwebp-dev libicu-dev libxml2-dev

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-configure  gd --with-webp

# Instal ekstensi PHP yang diperlukan untuk pengembangan
RUN docker-php-ext-install mysqli pdo pdo_mysql pdo_pgsql pgsql zip gd intl gettext xml exif

# Aktifkan mod_rewrite untuk Apache
RUN a2enmod rewrite headers deflate expires authz_core authz_groupfile setenvif 

# Set konfigurasi virtual host Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Aktifkan konfigurasi virtual host yang baru
RUN a2ensite 000-default.conf

# Restart Apache untuk menerapkan perubahan
RUN service apache2 restart

# Set folder proyek sebagai volume
VOLUME /var/www/html