version: '3'

services:
  php-7.4:
    container_name: php-7.4
    build:
      context: .
      dockerfile: Dockerfile-7.4
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_FOLDER}:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=1G
      - MEMORY_LIMIT=1G
      
  php-8.1:
    container_name: php-8.1
    build:
      context: .
      dockerfile: Dockerfile-8.1
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_FOLDER}:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=1G
      - MEMORY_LIMIT=1G

  php-8.2:
    container_name: php-8.2
    build:
      context: .
      dockerfile: Dockerfile-8.2
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_FOLDER}:/var/www/html
    depends_on:
      - mariadb
    environment:
      - UPLOAD_LIMIT=1G
      - MEMORY_LIMIT=1G

  mariadb:
    container_name: db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql